composer.json, composer.lock, src/Imgix/UrlHelper.php, tests/Imgix/Tests/UrlBuilderTest.php, tests/Imgix/Tests/UrlHelperTest.php
This will cause problems when trying to encode URLs with query parameters. Similar issues have cropped up in other imgix libraries, like imgix-rb: https://github.com/imgix/imgix-rb/commit/bf1e5966780dd111e244c168146dc15e1b2b25e4
=> UrlBuilder does not CGI-encode fully-qualified URLs

README.md, composer.json, src/Imgix/UrlBuilder.php, src/Imgix/UrlHelper.php, tests/Imgix/Tests/UrlBuilderTest.php, tests/Imgix/Tests/UrlHelperTest.php
This PR is aiming to fix an issue with urls that have for example tilde in their url.
There was a discussion with Pedro Aguilar from customer support about this.
Background
> Imgix PHP Library uses urlencode() in the UrlHelper converting ~ to %7E. Chrome will resolve this to ~ and the signed md5 hash won’t work.
Another approach with perhaps the same objective is in #26
=> Adding rawEncodePath parameter to createURL

src/Imgix/UrlHelper.php
This PR fixes a regression in version 1.2, as pointed out in #28.
@aronj care to take a look at this for me?
=> Ensure $path is a string in UrlHelper->formatPath

src/Imgix/UrlBuilder.php, src/Imgix/UrlHelper.php, tests/Imgix/Tests/UrlBuilderTest.php, tests/Imgix/Tests/UrlHelperTest.php
This PR fixes the path-encoding logic for this library, to bring it in line with other libraries in our SDK. The logic is as follows:
- **All paths are expected to be passed in unencoded.** If a path is provided that is already encoded, it will become double-encoded.
- **If the path matches `/^https?:\/\//`, it will be fully encoded, slashes and all.** In this case, we're assuming it's a fully-qualified URL (this is necessary for [web proxy sources](https://docs.imgix.com/setup/creating-sources/web-proxy)). We had previously been using `urlencode()` for this, but [version 1.2.0](https://github.com/imgix/imgix-php/releases/tag/1.2.0) introduced an option to use `rawurlencode()` instead. This PR removes that option and uses `rawurlencode()` in all cases. The general consensus in the PHP …
=> Fix path encoding

src/Imgix/UrlBuilder.php
Adds a `setIncludeLibraryParam` setter method in the same style as the other constructor options. Without it it's required to pass through all arguments to the constructor which is not ideal without named parameters.
Before:
``` php
$builder = new UrlBuilder(
'some-imgx-domain.example.com',
true,
"",
ShardStrategy::CRC,
false
);
```
After:
``` php
$builder = new UrlBuilder('some-imgx-domain.example.com');
$builder->setUseHttps(true);
$builder->setIncludeLibraryParam(false);
```
=> Add includeLibraryParam setter

.travis.yml, src/Imgix/UrlHelper.php, tests/Imgix/Tests/UrlHelperTest.php
Currently, if an already encoded URL is passed as path, it gets double encoded --`http%3A%2F%2Ffoo.bar%2Fbaz.png` encoded as `http%253A%252F%252Ffoo.bar%252Fbaz.png`.
This PR avoids double encoding only if the the input is a _valid_ encoded URL. If the URL is found to be invalid, it will be encoded as usual (`%` characters being replaced with `%25`).
The encoding is performed as usual for all other cases.
=> Don't double encode URLs

tests/Imgix/Tests/UrlBuilderTest.php
This PR replaces the deprecated `@expectedException` and `@expectedExceptionMessage` annotations with the preferred exception method equivalents.
=> fix: replace deprecated phpunit annotations with exception methods

src/Imgix/UrlHelper.php, tests/Imgix/Tests/UrlBuilderTest.php
Certain imgix URL parameters accept multiple comma-separated values, eg `auto=compress,format`. This PR will flatten nested arrays passed into `$params`, separating them by commas.
For example, the following scenario would previously throw an error:
```php
$params = array("auto" => array("compress","format"));
$url = $builder->createURL("bridge.png", $params);
```
After flattening the array, it should now produce the following URL:
```
https://demos.imgix.net/bridge.png?auto=compress%2Cformat
```
Special thanks to @xuneXTW for catching this.
=> fix: flatten nested array in $params

src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
Adds a validation that will throw an error if a user attempts to initialize a new `UrlBuilder` object with an invalid domain.
The validation criteria is based off of the same regex used on [dashboard.imgix.com](https://dashboard.imgix.com)
Fixes #10
=> fix: add domain validation at UrlBuilder initialization

README.md, src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
This PR begins the process of deprecating, and eventually removing, domain sharding from the imgix-php library.
The `UrlBuilder` object will now generate a warning when users attempt to initialize it by passing in multiple domains in the form of an array.
=> fix: deprecate domain sharding

README.md
This PR adds a link in the README to the [blog post](https://blog.imgix.com/2019/05/03/deprecating-domain-sharding), explaining the decision to remove the domain sharding feature from the imgix SDK.
Relates to #42
=> docs: add link to domain sharding deprecation blog post

README.md
Uses the svg version of the Travis build badge. Should have been included as part of #48 but got left out.
=> docs: use svg build badge

README.md
As a follow up to #48, use the badge directly from packagist to indicate the current package version.
Before:
After:
=> docs: use packagist badge on README

src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
To summarize the following, this PR changes the default behavior
of the `UrlBuilder` class. Before this change, the default behavior
used `http` by default. After this change, the default behavior uses
`https` __by default__.
When I began, I made a small change in the constructor definition and
ran the test. All passed (not intended, not expected). I removed the
change and began this PR by writing a _failing test_ first. I re-ran the
test suite and the test,`testExamplePlainUsesHttpsByDefault`, failed
as intended. I then made the appropriate change in the constructor
definition, re-ran the tests, all passed.
- first, I wrote a failing test; it tests that this SDK does use
https by default, it failed
- then the default constructor's default-parameter was changed to
use `$useHttps = true` …
=> feat: use https by default

CHANGELOG.md, README.md, composer.json, src/Imgix/UrlBuilder.php
This commit updates the release version throughout the project. The
version is being updated due to a change made to the default behavior
of the API. Prior to the change, `http` was used by default. Now,
`https` is being used by default. To ensure I've changed the version
everywhere that it appears, I `ripgrep`'d (grep) for "3.1.1".
After changing the version, I grepped for "3.2.0" with the following
results:
```text
composer.json
5:  "version": "3.2.0",
CHANGELOG.md
5:<a name="3.2.0"></a>
7:## [3.2.0](https://github.com/imgix/imgix-php/compare/3.0.0...3.2.0) (2020-03-31)
src/Imgix/UrlBuilder.php
7:    private $currentVersion = "3.2.0";
```
This squares with the modified files:
```text
modified:   CHANGELOG.md
modified:   composer.json
modified:   src/Imgix/UrlBuilder.php
modified: …
```
=> chore(release): 3.2.0

src/Imgix/UrlBuilder.php
This PR seeks to normalize the behavior of target widths (kit wide).
Prior, it was an error (python) to set start = stop when generating
a range of target width values. This has been relaxed and it is no longer
an error making generating target width lists of length 1 possible.
=> refactor: normalize behavior of target widths

src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
This PR removes the `ensure even` requirement on target widths and
updates the appropriate tests.
Previously, image target widths were required to be even integer values.
The original line of thought accounted for physical device pixel dimension
evenness; however, this is important only if images are rendered at full
viewport width.
Since this is not always the case, we wanted to include both odd and even
values here to give users more flexibility and to better meet user expectations:
i.e. if widths [115, …, 2121] were requested, then [116, …, 2122] could be
considered unexpected.
=> fix: remove ensure even requirement

src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
Prior to this PR, width `tol`erance was expected to be of type `int`
and within the range of `[1, 100]` or "one to one hundred percent."
Now, `tol` is expected to be a `float` in the range `[0.01, 1.0]` which
also represents "one to one hundred percent."
We have done this for consistency purposes, i.e. [imgix-core-js](https://github.com/imgix/imgix-core-js/blob/2c9d97a7ab54c7a8fec378732bdcb855cef41907/src/imgix-core-js.js#L25) uses
floating point values. Since `imgix-core-js` was impl'd first, we defer
to this tried/tested interface. This way, this feature is standard
and consistent kit-wide.
=> refactor: change tolerance from int -> float

README.md, tests/Imgix/Tests/ReadMeTest.php
This PR updates the readme for the custom srcsets feature set.
These changes not only reflect the **additional features** added, but
also try to pin down the **semantics** of our **syntax** and
documentation**.
Namely, the differentiation between `fixed` and `fluid-width` srcsets.
We currently construct two types of srcset attributes: those with `fixed`
widths and those with `fluid` widths.
**Fluid-widths vary**. A srcset attribute composed of target width pairs is
described as _fluid_ because each image candidate string denotes a
unique width-described resource.
**Fixed-widths are fixed**. A srcset attribute composed of pixel density
descriptors (ie. `1x, 2x, 3x`) is described as **fixed-width** because width
is held constant, while the pixel density descriptors vary.
Prior to this PR, …
=> docs(readme): update readme for custom srcset feat

src/Imgix/UrlBuilder.php, src/Imgix/Validator.php, tests/Imgix/Tests/ValidatorTest.php
This PR implements basic validation for `start`, `stop`, `tol`, and
`widths`.
**When invalid input is encountered an exception will be thrown.**
Specifically, a `InvalidArgumentException` is thrown detailing the error
state that has occurred.
We debated whether or not to throw exceptions in a few cases;
ultimately we have decided that error states should be clearly
defined and handled (both for us internally and for users).
What this means is that, in a few cases, our library will `throw`
which results in callers being immediately alerted of the error
state that caused the exception to be thrown (so that errors are
not propagated silently throughout application code).
This is an added layer of _safety_ to help ensure code that depends
on this library remains correct (w.r.t. it's usage of …
=> feat: validate custom srcsets

README.md, composer.lock
This PR changes any references from the master branch to the main branch, now that it is the default.
=> chore: change refs of master to main

.github/CODEOWNERS
This PR adds [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) to designate those responsible for maintaining this project to outside users/contributors. Currently, the default/only assignment points to @imgix/imgix-sdk-team.
=> chore: add project CODEOWNERS

README.md
Title says it all. I thought putting the standalone instructions underneath the Composer instructions flowed better.
=> docs: reorder install instruction to promote usage of composer

src/Imgix/UrlBuilder.php, tests/Imgix/Tests/UrlBuilderTest.php
This PR ensures a DPR-based SrcSet is generated when a fixed height is the only parameter value.
It removes tests that no longer apply to only having h as a param, and
adds tests that ensure the DPR `sercset` was generated correctly.
=> fix: dpr srcset when only h param

tests/Imgix/Tests/PathEncodingTest.php
This PR adds more path encoding tests.
This PR chose to make a new file for these tests. An argument could be make for leaving these inside the `buildURL` tests. For the sake of making these as easy to read and find as possible, they were left in a separate file.
=> test(encoding): add path encoding tests to image urls that resolve

.circleci/config.yml, .travis.yml
This PR updates the CI config to use CircleCI. It also updates the PHP versions to use the current LTS and stable versions.
=> chore: add circleci config

README.md
Explain easy and quick setup using composer command
=> Update Readme with composer command

src/Imgix/UrlHelper.php
Since no checks of array values with isset or so and just normal concatenation
=> Return the url and avoid the temp variable

.github/workflows/add-pr-to-project.yml
This PR changes the add pr to the project action title to better match what it's doing, adding opened PRs to the GH project board.
You can see the Action take place bellow with the updated information.
=> chore: update gh pr action

README.md
Updating the readme index to match the changes in #99
=> docs: update index and wording for install command

.circleci/config.yml, README.md, composer.json, composer.lock
Dropped support for PHP 7.x everywhere, since [PHP 7.4 reached EOL](https://www.php.net/supported-versions.php) a couple of days ago.
PHP 8.2 will release later this month, and I'll submit a separate PR to include that in CI scripts once it's out.
=> chore: bump minimum version requirements

composer.json, src/UrlBuilder.php, tests/UrlBuilderTest.php
=> chore(release): v4.0.0

src/UrlBuilder.php, src/UrlHelper.php, src/Validator.php, tests/UrlHelperTest.php, tests/ValidatorTest.php
Adds 3 tests to `UrlHelperTest.php` and 1 test to `ValidatorTest.php`. These tests brings the code base to 100% coverage.
Touches this piece of code in `UrlHelper.php`:
```php
22 if (!is_string($path) || strlen($path) < 1)
23     return '/';
```
Tests that unsetting parameters via `setParameter()` and `deleteParameter()` in `UrlHelper.php` works. It tests by first setting a value, and then either setting it to `null` or by using `deleteParameter()`.
---
Tests that negative values throws an exception in `validateWidths()`.
The `$widths == NULL` on line 46 in `Validator.php` actually was truthy if `$widths` was an empty array.
`testValidateWidthsEmptyArray()` did therefore pass, but not for the right reason. It was passing because of the loose comparison in $widths == NULL was throwing the …
=> test: add missing tests for 100% coverage
